### PR TITLE
Local scr

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by ancorgs** [comment]
Not sure if "local" express exactly the idea. Since I don't have a better suggestion, I'd probably change the direction of the question and would implement a ```#chroot?``` method.

**Comment by jreidinger** [comment]
so something like `#scr_chroot?` as I want emphasis that it is part of SCR, as WFM currently handling three different functonality and I cannot split it due to backward compatibility

**Comment by ancorgs** [comment]
Sounds good, yes.

**Comment by jreidinger** [comment]
@ancorgs updated

**Comment by ancorgs** [comment]
LGTM.

BTW, I'm not allowed to access the mentioned FATE, so I expect not many people being able.

**Pull request merged**
